spring:
  datasource:
    url: jdbc:mysql://${CLEARDB_DATABASE_URL}?serverTimezone=UTC#?allowPublicKeyRetrieval=true&amp;shutdown=true&amp;useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: validate
      connection:
        charset: utf8
        useUnicode: true
      show-sql: true
      properties:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
  schemas: db_migrate
  enabled: true
  validate-on-migrate: true
server:
  port: ${PORT:8080}
blog:
  title: WD pub
  subtitle: web disign pub
  telegram: MikeVS1
  email: mikevs63@gmail.com
  copyright: Mikhail Smirniskiy
  copyrightFrom: 2021
  liveTimeCaptcha: 1200000
  postLenth: 50
  commentLength: 3

