spring.datasource.url: jdbc:mysql://localhost:3306/diplom?serverTimezone=UTC#?allowPublicKeyRetrieval=true&amp;shutdown=true&amp;useSSL=false
spring.datasource.username: root
spring.datasource.password: test4321
spring.jpa.show-sql: true
spring:
  flyway:
  url: jdbc:mysql://localhost:3306/db_migrate?serverTimezone=UTC#?allowPublicKeyRetrieval=true&amp;shutdown=true&amp;useSSL=false
  username: root
  spring.datasource.password: test4321
  enabled: false
  validate-on-migrate: true
spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: create
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
