spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diplom?serverTimezone=UTC#?allowPublicKeyRetrieval=true&amp;shutdown=true&amp;useSSL=false
    username: root
    password: test4321
  jpa:
    hibernate:
      ddl-auto: validate
      connection:
        charset: utf8
        useUnicode: true
      show-sql: true
      properties:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
  schemas: db_migrate
  enabled: true
  validate-on-migrate: true

blog:
  title: WD pub
  subtitle: web disign pub
  telegram: MikeVS1
  email: mikevs63@gmail.com
  copyright: Mikhail Smirniskiy
  copyrightFrom: 2021
  liveTimeCaptcha: 1200000

